/**
 * SOAP MCP relay (Cloudflare Worker + Durable Objects).
 *
 * Lets AI apps reach a SOAP tab running on the hosted web app:
 *   AI app  --MCP (HTTPS)-->  /mcp/<room>     ┐
 *                                              ├─ one Durable Object per room relays calls
 *   SOAP tab --WebSocket-->   /bridge/<room>  ┘
 *
 * <room> is a long random secret generated by SOAP; knowing it is what lets an AI app reach that tab.
 * The relay stores nothing but MCP session ids; the tab applies (or refuses) every command.
 */
import { handleMcpHttp, TabCalls, classifyClient, ClientInfo } from '../../mcp/core';

export interface Env {
    ROOMS: DurableObjectNamespace;
    ALLOWED_ORIGINS?: string; // comma-separated origins allowed to open a SOAP tab link, e.g. https://soap.vercel.app
}

const ROOM_RE = /^[A-Za-z0-9_-]{32,128}$/;
const SESSION_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const MAX_SESSIONS = 50;

const CORS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, GET, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Accept, Authorization, Mcp-Session-Id, Mcp-Protocol-Version',
    'Access-Control-Expose-Headers': 'Mcp-Session-Id',
};

export default {
    async fetch(req: Request, env: Env): Promise<Response> {
        const url = new URL(req.url);
        if (url.pathname === '/' || url.pathname === '/health') {
            return new Response('SOAP MCP relay. Connect with the personal link shown in SOAP (plug icon → AI Bridges).', { headers: { 'Content-Type': 'text/plain' } });
        }
        const m = url.pathname.match(/^\/(mcp|bridge)\/([^/]+)\/?$/);
        if (!m || !ROOM_RE.test(m[2])) return new Response('Not found', { status: 404 });
        const [, kind, room] = m;

        if (kind === 'mcp' && req.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
        if (kind === 'bridge') {
            if (req.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
            const allowed = (env.ALLOWED_ORIGINS || '').split(',').map(o => o.trim()).filter(Boolean);
            const origin = req.headers.get('Origin') || '';
            if (allowed.length && !allowed.includes(origin)) return new Response('This SOAP address is not allowed to use the relay', { status: 403 });
        }
        return env.ROOMS.get(env.ROOMS.idFromName(room)).fetch(req);
    },
};

interface StoredSession extends ClientInfo { lastSeen: number }

export class Room implements DurableObject {
    private calls: TabCalls;

    constructor(private state: DurableObjectState, _env: Env) {
        this.calls = new TabCalls(msg => this.sendToTab(msg));
    }

    // The newest open tab socket (sockets survive hibernation; this object's memory doesn't)
    private tab(): WebSocket | null {
        let best: WebSocket | null = null, bestAt = -1;
        for (const ws of this.state.getWebSockets('tab')) {
            if (ws.readyState !== WebSocket.OPEN) continue;
            const at = (ws.deserializeAttachment() as { at?: number } | null)?.at ?? 0;
            if (at > bestAt) { best = ws; bestAt = at; }
        }
        return best;
    }

    private sendToTab(msg: unknown): boolean {
        const ws = this.tab();
        if (!ws) return false;
        try { ws.send(JSON.stringify(msg)); return true; } catch { return false; }
    }

    private async sessions(): Promise<Map<string, StoredSession>> {
        return this.state.storage.list<StoredSession>({ prefix: 's:' });
    }

    private async broadcastSessions() {
        const list = [...(await this.sessions())].map(([key, s]) => ({ id: key.slice(2), name: s.name, version: s.version, kind: classifyClient(s.name) }));
        this.sendToTab({ type: 'sessions', sessions: list });
    }

    async fetch(req: Request): Promise<Response> {
        const url = new URL(req.url);

        if (url.pathname.startsWith('/bridge/')) {
            const { 0: client, 1: server } = new WebSocketPair();
            for (const old of this.state.getWebSockets('tab')) {
                try { old.close(4000, 'Another SOAP tab took over the AI bridge'); } catch { /* already closed */ }
            }
            this.state.acceptWebSocket(server, ['tab']);
            server.serializeAttachment({ at: Date.now() });
            server.send(JSON.stringify({ type: 'hello', mode: 'relay' }));
            await this.broadcastSessions();
            return new Response(null, { status: 101, webSocket: client });
        }

        // MCP endpoint
        let body: unknown;
        if (req.method === 'POST') {
            const text = await req.text();
            if (text.length > 5_000_000) return new Response('Request too large', { status: 413, headers: CORS });
            try { body = text ? JSON.parse(text) : undefined; } catch { body = null; }
        }
        const storage = this.state.storage;
        const out = await handleMcpHttp(req.method, req.headers.get('Mcp-Session-Id') ?? undefined, body, {
            createSession: async client => {
                const all = await this.sessions();
                // Forget sessions of clients that stopped coming back
                const now = Date.now();
                const stale = [...all].filter(([, s]) => now - s.lastSeen > SESSION_TTL_MS).map(([k]) => k);
                const extra = [...all].filter(([k]) => !stale.includes(k)).sort((a, b) => a[1].lastSeen - b[1].lastSeen)
                    .slice(0, Math.max(0, all.size - stale.length - MAX_SESSIONS + 1)).map(([k]) => k);
                if (stale.length || extra.length) await storage.delete([...stale, ...extra]);
                const id = crypto.randomUUID();
                await storage.put(`s:${id}`, { ...client, lastSeen: now });
                await this.broadcastSessions();
                return id;
            },
            getSession: async id => {
                const s = await storage.get<StoredSession>(`s:${id}`);
                if (!s) return null;
                // Refresh at most every ten minutes
                if (Date.now() - s.lastSeen > 10 * 60 * 1000) await storage.put(`s:${id}`, { ...s, lastSeen: Date.now() });
                return { name: s.name, version: s.version };
            },
            deleteSession: async id => {
                if (await storage.delete(`s:${id}`)) await this.broadcastSessions();
            },
            callTab: (tool, args, client) => this.calls.call(tool, args, client),
        });
        return new Response(out.body ?? null, { status: out.status, headers: { ...out.headers, ...CORS } });
    }

    webSocketMessage(_ws: WebSocket, message: string | ArrayBuffer) {
        this.calls.receive(typeof message === 'string' ? message : new TextDecoder().decode(message));
    }

    webSocketClose(ws: WebSocket, code: number) {
        try { ws.close(code, 'closed'); } catch { /* already closed */ }
        if (!this.tab()) this.calls.failAll();
    }

    webSocketError() {
        if (!this.tab()) this.calls.failAll();
    }
}
